apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: yourown-chat
spec:
  image: southamerica-east1-docker.pkg.dev/gcloud-production-1/mattermost/mattermost
  imagePullPolicy: IfNotPresent
  version: latest
  # size: 5000users
  serviceAnnotations: {}
  ingress:
    enabled: false
    host: yourown.chat
    annotations:
      kubernetes.io/ingress.class: "nginx"
    tlsSecret: "yourown-chat-tls"
  mattermostEnv:
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
    - name: MM_SERVICESETTINGS_SITEURL
      value: "https://yourown.chat"
    - name: MM_SERVICESETTINGS_ENABLEUSERACCESSTOKENS
      value: "false"
    - name: MM_TEAMSETTINGS_TEAMMATENAMEDISPLAY
      value: "full_name"
    - name: MM_TEAMSETTINGS_LOCKTEAMMATENAMEDISPLAY
      value: "true"
    - name: MM_EMAILSETTINGS_ENABLEPUSHNOTIFICATIONS
      value: "true"
    - name: MM_EMAILSETTINGS_PUSHNOTIFICATIONCONTENTS
      value: "full"
    - name: MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS
      value: "true"
    - name: MM_SERVICESETTINGS_ENFORCEINCOMINGWEBHOOKCHANNELLOCKING
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLECOMMANDS
      value: "false"
    - name: MM_SERVICESETTINGS_ENABLEPOSTUSERNAMEOVERRIDE
      value: "false"
    - name: MM_SERVICESETTINGS_ENABLEPOSTICONOVERRIDE
      value: "false"
    - name: MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION
      value: "false"
    - name: MM_SERVICESETTINGS_DISABLEBOTSWHENOWNERISDEACTIVATED
      value: "true"
  # licenseSecret: ""
  database:
    external:
      secret: postgres-connection
  fileStore:
    external:
      url: storage.googleapis.com
      bucket: gcloud-production-1-mattermost-southamerica-east1
      secret: s3-credentials
  elasticSearch:
    host: ""
    username: ""
    password: ""
#  volumeMounts: {}
#  volumes: {}
  replicas: 1
  scheduling:
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: "2"
        memory: 3Gi
    affinity: {}