{{- range $name, $server := .Values.servers }}
{{- if and $server.enabled $server.serviceAccountName $server.gcpServiceAccountDeployParameter }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $server.serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: mcp-servers
  annotations:
    iam.gke.io/gcp-service-account: {{
      required
        (printf "Cloud Deploy parameter %s is required" $server.gcpServiceAccountDeployParameter)
        (get $.Values $server.gcpServiceAccountDeployParameter) | quote
    }}
{{- end }}
{{- end }}
{{- if and .Values.tunnel.enabled .Values.tunnel.serviceAccountName .Values.tunnel.gcpServiceAccountDeployParameter }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tunnel.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: mcp-servers
  annotations:
    iam.gke.io/gcp-service-account: {{
      required
        (printf "Cloud Deploy parameter %s is required" .Values.tunnel.gcpServiceAccountDeployParameter)
        (get .Values .Values.tunnel.gcpServiceAccountDeployParameter) | quote
    }}
{{- end }}
