apiVersion: batch/v1
kind: Job
metadata:
  name: mcp-dev-cleanup
  namespace: mcp-tunnel
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-dev-cleanup
    spec:
      serviceAccountName: mcp-dev-cleanup
      restartPolicy: Never
      priorityClassName: development
      containers:
        - name: cleanup-mcp-dev
          image: gcr.io/cloud-builders/kubectl@sha256:3744bfd3765ac2a09133a164fcd74c8468fac192af8accadbdfbccbb20643961
