{{- $root := . -}}
{{- range $instanceName, $instance := .Values.instances }}
{{- if and $root.Values.externalSecrets.database.enabled $instance.enabled $instance.database.externalSecret.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $instance.database.secret }}
  namespace: {{ $root.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $root.Values.externalSecrets.storeName }}
  target:
    name: {{ $instance.database.secret }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "{{ `{{ .datasource }}` }}"
        MM_SQLSETTINGS_DRIVERNAME: postgres
        MM_SQLSETTINGS_DATASOURCE: "{{ `{{ .datasource }}` }}"
  data:
    - secretKey: datasource
      remoteRef:
        key: {{ $instance.database.externalSecret.datasourceSecretId }}
    {{- end }}
{{- end }}
