{{- if .Values.externalSecrets.matterbridge.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matterbridge
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.storeName }}
  target:
    name: matterbridge
    creationPolicy: Owner
  data:
    - secretKey: MATTERBRIDGE_LOCAL_MM_TOKEN
      remoteRef:
        key: matterbridge-local-mattermost-token
    - secretKey: MATTERBRIDGE_LOCAL_MM_TEAM
      remoteRef:
        key: matterbridge-local-mattermost-team
    - secretKey: MATTERBRIDGE_LOCAL_MM_CHANNEL
      remoteRef:
        key: matterbridge-local-mattermost-channel
    - secretKey: MATTERBRIDGE_EXTERNAL_MM_SERVER
      remoteRef:
        key: matterbridge-external-mattermost-server
    - secretKey: MATTERBRIDGE_EXTERNAL_MM_TEAM
      remoteRef:
        key: matterbridge-external-mattermost-team
    - secretKey: MATTERBRIDGE_EXTERNAL_MM_TOKEN
      remoteRef:
        key: matterbridge-external-mattermost-token
    - secretKey: MATTERBRIDGE_EXTERNAL_MM_CHANNEL
      remoteRef:
        key: matterbridge-external-mattermost-channel
    - secretKey: MATTERBRIDGE_ROCKETCHAT_SERVER
      remoteRef:
        key: matterbridge-rocketchat-server
    - secretKey: MATTERBRIDGE_ROCKETCHAT_USER_ID
      remoteRef:
        key: matterbridge-rocketchat-user-id
    - secretKey: MATTERBRIDGE_ROCKETCHAT_TOKEN
      remoteRef:
        key: matterbridge-rocketchat-token
    - secretKey: MATTERBRIDGE_ROCKETCHAT_CHANNEL
      remoteRef:
        key: matterbridge-rocketchat-channel
    - secretKey: MATTERBRIDGE_TELEGRAM_TOKEN
      remoteRef:
        key: matterbridge-telegram-token
    - secretKey: MATTERBRIDGE_TELEGRAM_CHAT_ID
      remoteRef:
        key: matterbridge-telegram-chat-id
{{- end }}
