{{- $root := . -}}
{{- range $instanceName, $instance := .Values.instances }}
{{- if $instance.enabled }}
---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: {{ $instance.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  image: {{ $root.Values.mattermost.image.repository }}
  imagePullPolicy: IfNotPresent
  version: {{ $instance.imageTag | quote }}
  serviceAnnotations: {}
  ingress:
    enabled: false
    host: {{ $instance.ingress.host }}
    annotations:
      kubernetes.io/ingress.class: "nginx"
    tlsSecret: {{ $instance.ingress.tlsSecret | quote }}
  mattermostEnv:
{{- if eq $instance.fileStore.type "s3" }}
    - name: MM_FILESETTINGS_AMAZONS3SSE
      value: "true"
    - name: MM_FILESETTINGS_AMAZONS3SSL
      value: "true"
{{- end }}
    - name: MM_SERVICESETTINGS_SITEURL
      value: {{ $instance.siteUrl | quote }}
    - name: MM_SERVICESETTINGS_ENABLEUSERACCESSTOKENS
      value: "false"
    - name: MM_TEAMSETTINGS_TEAMMATENAMEDISPLAY
      value: "full_name"
    - name: MM_TEAMSETTINGS_LOCKTEAMMATENAMEDISPLAY
      value: "true"
    - name: MM_EMAILSETTINGS_ENABLEPUSHNOTIFICATIONS
      value: "true"
    - name: MM_EMAILSETTINGS_PUSHNOTIFICATIONCONTENTS
      value: "full"
    - name: MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS
      value: "true"
    - name: MM_SERVICESETTINGS_ENFORCEINCOMINGWEBHOOKCHANNELLOCKING
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLECOMMANDS
      value: "false"
    - name: MM_SERVICESETTINGS_ENABLEPOSTUSERNAMEOVERRIDE
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEPOSTICONOVERRIDE
      value: "true"
    - name: MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION
      value: "false"
    - name: MM_SERVICESETTINGS_DISABLEBOTSWHENOWNERISDEACTIVATED
      value: "true"
  database:
    external:
      secret: {{ $instance.database.secret }}
  fileStore:
{{- if eq $instance.fileStore.type "s3" }}
    external:
      url: storage.googleapis.com
      bucket: {{ $instance.fileStore.bucketName }}
      secret: {{ $instance.fileStore.s3Secret }}
{{- else if eq $instance.fileStore.type "local" }}
    local:
      enabled: true
      storageSize: {{ $instance.fileStore.storageSize | quote }}
      accessModes:
{{ toYaml $instance.fileStore.accessModes | indent 8 }}
{{- end }}
  elasticSearch:
    host: ""
    username: ""
    password: ""
  replicas: 1
  scheduling:
    resources:
{{ toYaml $root.Values.mattermost.resources | indent 6 }}
    affinity: {}
{{- end }}
{{- end }}
