{{- $root := . -}}
{{- range $instanceName, $instance := .Values.instances }}
{{- if $instance.enabled }}
---
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: {{ $instance.name }}
  namespace: {{ $root.Release.Namespace }}
spec:
  image: {{ $root.Values.mattermost.image.repository }}
  imagePullPolicy: {{ $root.Values.mattermost.image.pullPolicy | default "Always" | quote }}
  version: {{ $instance.imageTag | quote }}
  serviceAnnotations: {}
  ingress:
    enabled: false
    host: {{ $instance.ingress.host }}
    annotations:
      kubernetes.io/ingress.class: "nginx"
    tlsSecret: {{ $instance.ingress.tlsSecret | quote }}
  mattermostEnv:
{{- with $instance.env }}
{{ toYaml . | indent 4 }}
{{- end }}
    - name: YOUROWN_CHAT_IMAGE_TAG
      value: {{ $instance.imageTag | quote }}
    - name: YOUROWN_CHAT_IMAGE_DIGEST
      value: {{ $instance.imageDigest | default "" | quote }}
  database:
    external:
      secret: {{ $instance.database.secret }}
  fileStore:
{{- if eq $instance.fileStore.type "s3" }}
    external:
      url: storage.googleapis.com
      bucket: {{ $instance.fileStore.bucketName }}
      secret: {{ $instance.fileStore.s3Secret }}
{{- else if eq $instance.fileStore.type "local" }}
    local:
      enabled: true
      storageSize: {{ $instance.fileStore.storageSize | quote }}
      accessModes:
{{ toYaml $instance.fileStore.accessModes | indent 8 }}
{{- end }}
  elasticSearch:
    host: ""
    username: ""
    password: ""
  replicas: 1
  scheduling:
    resources:
{{ toYaml ($instance.resources | default $root.Values.mattermost.resources) | indent 6 }}
    affinity: {}
{{- end }}
{{- end }}
