{{- if .Values.externalSecrets.matterbridge.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matterbridge
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecrets.storeName }}
  target:
    name: matterbridge
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.matterbridge.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
    {{- end }}
{{- end }}
