{{- $root := . -}}
{{- range $instanceName, $instance := .Values.instances }}
{{- if and $root.Values.externalSecrets.s3.enabled $instance.enabled (eq $instance.fileStore.type "s3") }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $instance.fileStore.s3Secret }}
  namespace: {{ $root.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $root.Values.externalSecrets.storeName }}
  target:
    name: {{ $instance.fileStore.s3Secret }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ `{{ .access_key }}` }}"
        secretkey: "{{ `{{ .secret_key }}` }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: {{ $root.Values.externalSecrets.s3.accessKeySecretId }}
    - secretKey: secret_key
      remoteRef:
        key: {{ $root.Values.externalSecrets.s3.secretKeySecretId }}
      {{- end }}
{{- end }}
