apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.transportApi }}
  namespace: {{ .Values.namespaces.edge }}
  labels:
    app: transport
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "transport_api_gsa is required" .Values.transport_api_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.authApi }}
  namespace: {{ .Values.namespaces.edge }}
  labels:
    app: auth
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "auth_api_gsa is required" .Values.auth_api_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityApi }}
  namespace: {{ .Values.namespaces.identity }}
  labels:
    app: api
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_api_gsa is required" .Values.identity_api_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityAdmin }}
  namespace: {{ .Values.namespaces.identity }}
  labels:
    app: admin
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_admin_gsa is required" .Values.identity_admin_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityMigrate }}
  namespace: {{ .Values.namespaces.identity }}
  labels:
    app: migrate
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_migrate_gsa is required" .Values.identity_migrate_gsa | quote }}
automountServiceAccountToken: false
{{- if .Values.yourown_chat_control_api_enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.controlApi }}
  namespace: {{ .Values.namespaces.control }}
  labels:
    app: control
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "backend_control_api_gsa is required" .Values.backend_control_api_gsa | quote }}
automountServiceAccountToken: false
{{- end }}
