apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityApi }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: yourown-chat-identity-api
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_api_gsa is required" .Values.identity_api_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityAdmin }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: yourown-chat-identity-admin
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_admin_gsa is required" .Values.identity_admin_gsa | quote }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.identityMigrate }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: yourown-chat-identity-migrate
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "identity_migrate_gsa is required" .Values.identity_migrate_gsa | quote }}
automountServiceAccountToken: false
{{- if .Values.yourown_chat_control_api_enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.controlApi }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: yourown-chat-control-api
    {{- include "yourown-chat.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "backend_control_api_gsa is required" .Values.backend_control_api_gsa | quote }}
automountServiceAccountToken: false
{{- end }}
