apiVersion: v1
kind: Service
metadata:
  name: transport
  namespace: {{ .Values.namespaces.edge }}
spec:
  selector: { app: transport }
  ports:
    - { name: http, port: 8084, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: {{ .Values.namespaces.edge }}
spec:
  selector: { app: auth }
  ports:
    - { name: http, port: 8083, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespaces.identity }}
spec:
  selector: { app: api }
  ports:
    - { name: http, port: 8081, targetPort: http }
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: {{ .Values.namespaces.identity }}
spec:
  type: ClusterIP
  selector: { app: admin }
  ports:
    - { name: http, port: 8082, targetPort: http }
{{- if .Values.yourown_chat_control_api_enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: control
  namespace: {{ .Values.namespaces.control }}
spec:
  selector: { app: control }
  ports:
    - { name: http, port: 8080, targetPort: http }
{{- end }}
