apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-control-api-gcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agent-platform.labels" . | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/{{ required "agent_secret_project is required" .Values.agent_secret_project }}/secrets/backend-control-api-token/versions/latest"
        path: "workflow-id-key"
