apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: __DB_EXTERNAL_SECRET__
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: __DB_EXTERNAL_SECRET__
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DB_CONNECTION_STRING: "{{ .datasource }}"
        MM_SQLSETTINGS_DRIVERNAME: postgres
        MM_SQLSETTINGS_DATASOURCE: "{{ .datasource }}"
  data:
    - secretKey: datasource
      remoteRef:
        key: __DB_SECRET_ID__