apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: __PROJECT_ID__
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-connection
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: postgres-connection
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MM_SQLSETTINGS_DRIVERNAME: postgres
        MM_SQLSETTINGS_DATASOURCE: "{{ .datasource }}"
        MM_SQLSETTINGS_DATASOURCEREPLICAS: "[]"
  data:
    - secretKey: datasource
      remoteRef:
        key: mattermost-db-datasource
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
  namespace: mattermost
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-manager
  target:
    name: s3-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accesskey: "{{ .access_key }}"
        secretkey: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: mattermost-s3-access-key
    - secretKey: secret_key
      remoteRef:
        key: mattermost-s3-secret-key